# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box = "centos65"

  config.vm.define "mediawiki" do |mediawiki|
    mediawiki.vm.hostname = "mediawiki.puppeels.mylezeem.com"

    mediawiki.vm.synced_folder ".", "/vagrant", type: "rsync"
    mediawiki.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
    mediawiki.vm.provision "shell", inline: "yum -y update puppetlabs-release"
    mediawiki.vm.provision "shell", inline: "yum -y update puppet"
    mediawiki.vm.provision "shell", inline: "service iptables stop"

    mediawiki.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = 'rsync'
      puppet.module_path = 'modules'
      puppet.hiera_config_path = 'hiera.yaml'
      #puppet.options = '--debug --version'
    end
  end

end
