#
# Forge
#

#
# profile::base
#
mod 'account',
  :git => 'https://github.com/Mylezeem/puppet-account.git',
  :ref => 'multiple_accounts'
mod 'profile',
  :git => 'https://github.com/Mylezeem/puppeels.git',
  :ref => 'master'
mod 'puppetlabs/ntp'
mod 'saz/sudo'
mod 'saz/ssh'
mod 'stahnma/epel'

#
# profile::monitoring::agent::sensu
#
mod 'sensu/sensu'


#
# profile::monitoring::server::sensu
#
mod 'puppetlabs/rabbitmq'
mod 'thomasvandoren/redis'

#
# profile::logging::agent::fluentd
#
mod 'srf/fluentd'

#
# profile::logging::server::fluentd
#
mod 'elasticsearch/elasticsearch'
mod 'kibana3',
  :git => 'https://github.com/thejandroman/kibana3.git'
mod 'puppetlabs/java'

#
# Common
#
mod 'gentoo/portage'
mod 'maestrodev/wget'
mod 'mhuffnagle/make'
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/firewall'
mod 'puppetlabs/gcc'
mod 'puppetlabs/git'
mod 'puppetlabs/inifile'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/xinetd'
