# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box = "centos65"


  config.vm.define "monitor" do |monitor|
    monitor.vm.hostname = "monitor.puppeels.mylezeem.com"

    monitor.vm.synced_folder ".", "/vagrant", type: "rsync"
    monitor.vm.provision "shell", inline: "yum -y update puppetlabs-release"
    monitor.vm.provision "shell", inline: "yum -y update puppet"
    monitor.vm.provision "shell", inline: "service iptables stop"

    monitor.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = 'rsync'
      puppet.module_path = 'modules'
      puppet.hiera_config_path = 'hiera.yaml'
    end
  end

  config.vm.define "log" do |log|
    log.vm.hostname = "log.puppeels.mylezeem.com"

    log.vm.synced_folder ".", "/vagrant", type: "rsync"
    log.vm.provision "shell", inline: "yum -y update puppetlabs-release"
    log.vm.provision "shell", inline: "yum -y update puppet"
    log.vm.provision "shell", inline: "yum -y install libcurl-devel"
    log.vm.provision "shell", inline: "service iptables stop"

    log.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = 'rsync'
      puppet.module_path = 'modules'
      puppet.hiera_config_path = 'hiera.yaml'
    end

    log.vm.provision "shell", inline: "cp /vagrant/misc/dasbhoard_apache.json /opt/kibana3/src/app/dashboards/"
  end

  config.vm.define "web001" do |web001|
    web001.vm.hostname = "web001.puppeels.mylezeem.com"

    web001.vm.synced_folder ".", "/vagrant", type: "rsync"
    web001.vm.provision "shell", inline: "yum -y update puppetlabs-release"
    web001.vm.provision "shell", inline: "yum -y update puppet"
    web001.vm.provision "shell", inline: "service iptables stop"

    web001.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = 'rsync'
      puppet.module_path = 'modules'
      puppet.hiera_config_path = 'hiera.yaml'
    end
  end

  config.vm.define "web002" do |web002|
    web002.vm.hostname = "web002.puppeels.mylezeem.com"

    web002.vm.synced_folder ".", "/vagrant", type: "rsync"
    web002.vm.provision "shell", inline: "yum -y update puppetlabs-release"
    web002.vm.provision "shell", inline: "yum -y update puppet"
    web002.vm.provision "shell", inline: "service iptables stop"

    web002.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = 'rsync'
      puppet.module_path = 'modules'
      puppet.hiera_config_path = 'hiera.yaml'
    end
  end


end
