#
# Forge
#

#
# profile::base
#
mod 'account',
  :git => 'https://github.com/Mylezeem/puppet-account.git',
  :ref => 'multiple_accounts'
mod 'profile',
  :git => 'https://github.com/Mylezeem/puppeels.git',
  :ref => 'master'
mod 'puppetlabs/ntp'
mod 'saz/sudo'
mod 'saz/ssh'
mod 'stahnma/epel'

#
# Pentaho
#
mod 'pentaho',
  :git => 'https://github.com/Mylezeem/puppet-pentaho.git'

mod 'archive',
  :git => 'https://github.com/camptocamp/puppet-archive.git'
mod 'maestrodev/wget'
mod 'puppetlabs/tomcat'



#
# Common
#
mod 'puppetlabs/java'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/mysql'
mod 'yguenane/mariadbrepo'
mod 'nanliu/staging'
mod 'domcleal/augeasproviders'
