# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vm.box = "centos65"

  config.vm.define "pentaho" do |pentaho|
    pentaho.vm.hostname = "pentaho.puppeels.mylezeem.com"

    pentaho.vm.synced_folder ".", "/vagrant", type: "rsync"
    pentaho.vm.provision "shell", inline: "yum -y update puppetlabs-release"
    pentaho.vm.provision "shell", inline: "yum -y update puppet"
    pentaho.vm.provision "shell", inline: "service iptables stop"

    pentaho.vm.provision "puppet" do |puppet|
      puppet.synced_folder_type = 'rsync'
      puppet.module_path = 'modules'
      puppet.hiera_config_path = 'hiera.yaml'
      puppet.options="--verbose --debug"
    end
  end

end
